version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db

  notifications:
    build:
      context: .
      dockerfile: apps/notifications/Dockerfile
    container_name: notifications
    restart: always
    ports:
      - "3002:3002"
    networks:
      - app

  users:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    container_name: users
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - notifications
    networks:
      - app
      - db

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    restart: always
    depends_on:
      - users
    ports:
      - "3000:3000"
    networks:
      - app

volumes:
  postgres-data:

networks:
  app:
    name: app
    driver: bridge
  db:
    name: db
