version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-private

  rabbitmq:
    build:
      context: .
      dockerfile: apps/notifications/rmq.Dockerfile
    container_name: rabbitmq
    hostname: rabbitmq
    env_file:
      - .env
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app-private

  notifications:
    build:
      context: .
      dockerfile: apps/notifications/Dockerfile
    container_name: notifications
    restart: always
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    networks:
      - app-private

  users:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    container_name: users
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - notifications
      - rabbitmq
    networks:
      - app-private

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    restart: always
    depends_on:
      - users
    ports:
      - "3000:3000"
    networks:
      - app-public
      - app-private

volumes:
  postgres-data:

networks:
  app-public:
    name: app-public
    external: true
  app-private:
    name: app-private
    external: false
